<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BIJILI" name="Test" tests="1" failures="1" timestamp="16 Oct 2020 19:05:34 GMT" time="20.269" errors="0">
  <testcase name="WebShop_Demo" time="7.761" classname="Testcases.Demo_Web_Shop">
    <failure type="java.lang.AssertionError" message="expected [atest@gmail.com] but found [My account]">
      <![CDATA[java.lang.AssertionError: expected [atest@gmail.com] but found [My account]
	at PageObjects.Login.Loginto(Login.java:37)
	at Testcases.Demo_Web_Shop.WebShop_Demo(Demo_Web_Shop.java:41)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- WebShop_Demo -->
</testsuite> <!-- Test -->
