<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="20269" started-at="2020-10-16T19:05:14Z" finished-at="2020-10-16T19:05:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="20269" started-at="2020-10-16T19:05:14Z" finished-at="2020-10-16T19:05:34Z">
      <class name="Testcases.Demo_Web_Shop">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String)[pri:0, instance:Testcases.Demo_Web_Shop@604ed9f0]" name="setup" is-config="true" duration-ms="11475" started-at="2020-10-17T00:35:14Z" finished-at="2020-10-17T00:35:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://demowebshop.tricentis.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="WebShop_Demo()[pri:0, instance:Testcases.Demo_Web_Shop@604ed9f0]" name="WebShop_Demo" duration-ms="7761" started-at="2020-10-17T00:35:26Z" finished-at="2020-10-17T00:35:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [atest@gmail.com] but found [My account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [atest@gmail.com] but found [My account]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at PageObjects.Login.Loginto(Login.java:37)
	at Testcases.Demo_Web_Shop.WebShop_Demo(Demo_Web_Shop.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- WebShop_Demo -->
        <test-method status="PASS" signature="teardown(org.testng.ITestResult)[pri:0, instance:Testcases.Demo_Web_Shop@604ed9f0]" name="teardown" is-config="true" duration-ms="990" started-at="2020-10-17T00:35:33Z" finished-at="2020-10-17T00:35:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=WebShop_Demo status=FAILURE method=Demo_Web_Shop.WebShop_Demo()[pri:0, instance:Testcases.Demo_Web_Shop@604ed9f0] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Testcases.Demo_Web_Shop -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
