<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CA0RA0D" name="Test" tests="1" failures="1" timestamp="19 May 2022 02:50:34 GMT" time="36.922" errors="0">
  <testcase name="WebShop_Demo" time="17.776" classname="Testcases.Task1">
    <failure type="java.lang.AssertionError" message="expected [Successfully Saved] but found [By.xpath: //*[text()=&amp;apos;Successfully Saved&amp;apos;]]">
      <![CDATA[java.lang.AssertionError: expected [Successfully Saved] but found [By.xpath: //*[text()='Successfully Saved']]
	at PageObjects.AddUser.AddUser_Task1(AddUser.java:38)
	at Testcases.Task1.WebShop_Demo(Task1.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- WebShop_Demo -->
</testsuite> <!-- Test -->
